# Generated by Django 3.1.4 on 2020-12-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201220_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='custom_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='social_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
