# Generated by Django 3.1.4 on 2020-12-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201225_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='custom_name',
        ),
    ]
