# Generated by Django 3.1.5 on 2021-03-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_student_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='photo',
            new_name='picture',
        ),
    ]
